# Use ROS2 Humble base image
FROM dustynv/l4t-pytorch:r36.4.0

# install packages
RUN apt-get update && apt-get install -q -y --no-install-recommends \
    dirmngr \
    gnupg2 \
    curl \
    wget \
    zip \
    unzip \
    vim \
    git \
    && rm -rf /var/lib/apt/lists/*

# install ros and build tools
ENV ROS_DISTRO humble
ENV LANG en_US.UTF-8
ENV LC_ALL en_US.UTF-8
RUN apt update && apt install -y locales
RUN locale-gen en_US en_US.UTF-8
RUN update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
RUN apt install -y software-properties-common
RUN add-apt-repository -y universe 
RUN curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
RUN echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | tee /etc/apt/sources.list.d/ros2.list > /dev/null
RUN apt update && apt install -y ros-$ROS_DISTRO-desktop python3-argcomplete python3-colcon-common-extensions python3-rosdep


# install ros2 packages
RUN apt-get update && apt-get install -y --no-install-recommends \
    ros-humble-ros-core \
    ros-humble-ackermann-msgs \
    && rm -rf /var/lib/apt/lists/*

# install bootstrap tools
RUN apt-get update && apt-get install --no-install-recommends -y \
    build-essential \
    git \
    python3-colcon-common-extensions \
    python3-colcon-mixin \
    python3-rosdep \
    python3-vcstool \
    && rm -rf /var/lib/apt/lists/*

# bootstrap rosdep
RUN rosdep init && \
  rosdep update --rosdistro $ROS_DISTRO

# setup colcon mixin and metadata
RUN colcon mixin add default \
      https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml && \
    colcon mixin update && \
    colcon metadata add default \
      https://raw.githubusercontent.com/colcon/colcon-metadata-repository/master/index.yaml && \
    colcon metadata update

# install ros2 packages
RUN apt-get update && apt-get install -y --no-install-recommends \
    ros-humble-ros-base \
    && rm -rf /var/lib/apt/lists/*

# Set the working directory to the main folder of your repository
WORKDIR /UniLuFP

# Install necessary dependencies
RUN apt-get update && apt-get install -y \
    python3-pip \
    ros-humble-rclpy \
    ros-humble-geometry-msgs \
    ros-humble-teleop-twist-keyboard \
    git \
    byobu \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /UniLuFP
COPY ./requirements.txt .
# Install Python dependencies
RUN python3 -m pip install --no-cache-dir -r requirements.txt

# Github repositories
WORKDIR /UniLuFP/ros_ws/src
COPY ./repositories.yaml .
RUN vcs import --input repositories.yaml --recursive .

RUN git clone https://github.com/aky-u/LevionArm.git \
 && cd LevionArm \
 && git submodule set-url cubemars_hardware https://github.com/aky-u/cubemars_hardware.git \
 && git submodule set-url leptrino_force_torque https://github.com/aky-u/leptrino_force_torque.git \
 && git submodule update --init --recursive

RUN apt-get update && apt-get install -y \
 && rosdep install --from-paths . --ignore-src -r -y

# Source ROS2 setup
SHELL ["/bin/bash", "-c"]
RUN echo "source /opt/ros/humble/setup.bash" >> ~/.bashrc

WORKDIR /UniLuFP/ros_ws
RUN apt-get update && apt-get install -y \
    ros-${ROS_DISTRO}-vrpn-mocap \
    netbase \
    && rm -rf /var/lib/apt/lists/*
RUN colcon build --symlink-install

# Source ROS2 workspace setup
RUN echo "source /UniLuFP/ros_ws/install/setup.bash" >> ~/.bashrc

WORKDIR /UniLuFP/ros_ws
# Default command
COPY ./ros_entrypoint.sh /
ENTRYPOINT ["/ros_entrypoint.sh"]
CMD ["bash"]