[General]
   TcpServerPort=5760
   ReportStats=false
   MavlinkDialect=common
   # DebugLogLevel=trace

[UartEndpoint serial0]
   Device=/dev/ttyPX4
   Baud=2000000

[UdpEndpoint local]
   Mode=normal
   Address=127.0.0.1
   Port=14550