import mujoco
import os
import xml.etree.ElementTree as ET

"""
This script exports a MuJoCo MJCF model from a URDF file.
It modifies the MJCF to include a floor, lighting, a floating base, and actuators.
It also rewrites mesh file paths to ensure they are correctly referenced.

TODO: Need to solve the path issue for the mesh files.

Usage:
    python export_mj_model.py
"""

def export_mj_model(input_urdf, output_mjcf):
    """
    Exports and modifies a MuJoCo MJCF model from a URDF file.
    Adds floor, lighting, floating base, and actuators.
    """
    # Convert URDF to MJCF
    model = mujoco.MjModel.from_xml_path(input_urdf)
    mujoco.mj_saveLastXML(output_mjcf, model)

    # Load MJCF XML for editing
    tree = ET.parse(output_mjcf)
    root = tree.getroot()

    # Add autogenerated comment
    comment = ET.Comment("==============================================================")
    comment.tail = "\n"
    root.insert(0, comment)
    comment = ET.Comment("This MJCF model is autogenerated from a URDF file.")
    comment.tail = "\n"
    root.insert(1, comment)
    comment = ET.Comment("It is not recommended to modify this file directly.")
    comment.tail = "\n"
    root.insert(2, comment)
    comment = ET.Comment("==============================================================")
    comment.tail = "\n"
    root.insert(3, comment) # TODO: this is suck

    # Rewrite mesh file paths
    asset = root.find("asset")
    if asset is not None:
        for mesh in asset.findall("mesh"):
            old_file = mesh.get("file")
            if old_file and (old_file.endswith(".STL") or old_file.endswith(".stl")):
                new_path = f"../urdf/{old_file}"
                mesh.set("file", new_path)

    # Rewrite option (make if not exist)
    option = root.find("option")
    if option is None:
        option = ET.SubElement(root, "option")
    option.set("integrator", "RK4")  # Set integrator to RK4
    option.set("timestep", "0.002")  # Set timestep to 0.002 seconds
    option.set("gravity", "0 0 0")  # Set gravity to Earth's gravity

    # Remake body structure
    worldbody = root.find("worldbody")
    if worldbody is not None:
        # Add floor
        ET.SubElement(worldbody, "geom", {
            "name": "floor",
            "type": "plane",
            "pos": "0 0 0",
            "size": "5 5 0.1",
            "rgba": "0.8 0.9 0.8 1",
            "contype": "1",
            "conaffinity": "1"
        })

        # Add light
        ET.SubElement(worldbody, "light", {
            "name": "main_light",
            "pos": "0 0 3",
            "dir": "0 0 -1",
            "diffuse": "1 1 1",
            "specular": "0.3 0.3 0.3"
        })

    # #  Make base a floating link (freejoint)
    # first_body = worldbody.find("body")
    # if first_body is not None and first_body.find("freejoint") is None:
    #     ET.SubElement(first_body, "freejoint", {"name": "floating_base"})

    # Add thrusters to the base body
    first_body = worldbody.find("base_link")
    if first_body is not None:
        # Add site to put thrusters
        thrust_num = 8
        for i in range(thrust_num):
            ET.SubElement(first_body, "site", {
                "name": f"thruster_{i+1}",
                "pos": f"{0.1 * i} 0 0.1",
                "size": "0.05",
                "type": "sphere",
                "rgba": "1 0 0 1"
            })

    # ET.SubElement(actuators, "position", {
    #     "name": "act_joint1",
    #     "joint": "joint1",  # ← your actual joint name
    #     "ctrlrange": "-1 1",
    #     "kp": "100"
    # })

    # Save the modified MJCF
    tree.write(output_mjcf)
    print(f"Modified MJCF model saved to {output_mjcf}")


if __name__ == "__main__":
    current_path = __file__.replace("export_mj_model.py", "")
    
    input_urdf = os.path.join(current_path, "..", "urdf", "pingu.urdf")
    output_mjcf = os.path.join(current_path, "pingu.xml")

    export_mj_model(input_urdf, output_mjcf)
    print(f"Exported MJCF model to {output_mjcf}")